import Head from "next/head";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import requests from "../utils/requests";
import Results from "../components/Results";

export default function Home({ results }) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <Results results={results} />
    </div>
  );
}
// 27638490
export async function getServerSideProps(context) {
  const genre = context.query.genre;
  console.log(genre);

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrends.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
